[docs] Require the removal of all non-CentOS base kernels
oracle/centos2ol pull request #5
Opened 2020-12-11 20:40 UTC by Djelibeybi

Our SecureBoot shim can only boot Oracle signed kernels and
we can only switch the standard CentOS kernel versions to our
signed versions. So document the need to remove any non-CentOS
kernels before switching.

Signed-off-by: Avi Miller <avi.miller@oracle.com>

2020-12-11 23:03 UTC, mark-au requested changes

2020-12-11 23:03 UTC, mark-au commented on README.md
> +
Maybe we could give an example of how to identify them? I haven't tested but I think this would cover it:
`$ sudo rpm -qa kernel* --qf "%{NAME}|%{VERSION}|%{RELEASE}|%{VENDOR}|%{PACKAGER}\n" | grep -v "CentOS"``

2020-12-11 23:05 UTC, Djelibeybi commented on README.md
> +1. Remove all packages from and disable all non-CentOS repositories. You can re-enable the repos and reinstall the packages them after the switch.
I'm not _just_ worried about kernels. I'm _also_ worried about `dkms` modules and other kernel-modifying ephemera.

2020-12-11 23:14 UTC, mark-au commented on README.md
> +1. Remove all packages from and disable all non-CentOS repositories. You can re-enable the repos and reinstall the packages them after the switch.
Maybe we can make a more kernel/module specific comment? I'm imagining a system running monitoring/logging from vendorA, config management from vendorB and inhouse applications/scripts. Asking them to remove those RPMs and reinstall may make a user worry about the switch

2020-12-11 23:19 UTC, Djelibeybi commented on README.md
> +1. Remove all packages from and disable all non-CentOS repositories. You can re-enable the repos and reinstall the packages them after the switch.
Fair point. I shall noodle on it over the weekend.

2020-12-11 23:27 UTC, Djelibeybi commented on README.md
> +
That may not list the CentOS Plus kernels: https://wiki.centos.org/AdditionalResources/Repositories/CentOSPlus

2020-12-16 01:56 UTC, mark-au approved these changes

2020-12-16 02:00 UTC, merged